/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Vo1_aliases.h"
#include "Vo1.h"
#include "CapSense.h"
#include "CapSense_CSHL.h"
#include "CapSense_Pins.h"
#include "CapSense_TunerHelper.h"
#include "ADC.h"
#include "WaveDAC8.h"
#include "Control_Reg.h"
#include "Vo2_aliases.h"
#include "Vo2.h"
#include "Button_Module.h"
#include "Pin_SW3_aliases.h"
#include "Pin_SW3.h"
#include "Pin_SW2_aliases.h"
#include "Pin_SW2.h"
#include "Clk_Tmr_Button.h"
#include "Timer_Button.h"
#include "isr_Tmr_Button.h"
#include "VDAC8.h"
#include "PGA.h"
#include "LCD_Seg.h"
#include "LCD_Seg_Pins.h"
#include "DAC_WC1.h"
#include "DAC_WC2.h"
#include "UART_1.h"
#include "MatrixKbLED.h"
#include "Clock_500Hz.h"
#include "LCD_Char.h"
#include "USBUART_1.h"
#include "USBUART_1_audio.h"
#include "USBUART_1_cdc.h"
#include "USBUART_1_hid.h"
#include "USBUART_1_midi.h"
#include "USBUART_1_pvt.h"
#include "USBUART_1_cydmac.h"
#include "USBUART_1_msc.h"
#include "CapSense_CompCH0.h"
#include "CapSense_IdacCH0.h"
#include "CapSense_AMuxCH0.h"
#include "CapSense_IntClock.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "ADC_Bypass_aliases.h"
#include "ADC_Bypass.h"
#include "WaveDAC8_DacClk.h"
#include "WaveDAC8_Wave1_DMA_dma.h"
#include "WaveDAC8_Wave2_DMA_dma.h"
#include "WaveDAC8_IDAC8.h"
#include "LCD_Seg_Int_Clock.h"
#include "LCD_Seg_Lcd_Dma_dma.h"
#include "LCD_Seg_Frame_Dma_dma.h"
#include "LCD_Seg_TD_DoneInt.h"
#include "UART_1_IntClock.h"
#include "MatrixKbLED_isr_MKbLED.h"
#include "LCD_Char_LCDPort_aliases.h"
#include "LCD_Char_LCDPort.h"
#include "USBUART_1_Dm_aliases.h"
#include "USBUART_1_Dm.h"
#include "USBUART_1_Dp_aliases.h"
#include "USBUART_1_Dp.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

